name: flutter_omni_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_sheet_localization: ^5.1.1
  #state managment
  flutter_bloc: ^8.0.1
  #dependency inyection
  get_it: ^7.2.0
  #logs
  logger: ^1.1.0
  #inmutable class generator
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  #Http client
  http: ^0.13.5
  #network connectivity
  connectivity_plus: ^2.3.5
  google_fonts: ^2.1.0
  #testing
  mockito: ^5.2.0
  bloc_test: ^9.0.3
  #package info
  package_info_plus: ^1.3.0
  # Image cache
  extended_image: ^6.1.0
  # svg images
  websafe_svg: ^2.0.0+2
  # to reconize equality comparision
  equatable: ^2.0.5
  #shimmers
  shimmer: ^2.0.0
  # to show pdfs 
  native_pdf_view: ^6.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: null

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    style: dot-delimiter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/pdf/RODRIGO_PORRAS.pdf
flutter_intl:
  enabled: true
